config/routes.rb
Rails.application.routes.draw do
  root 'staticpages#home'

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :tasks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates_presence_of :title
  has_many :lists


  def self.by_title(order = 'asc')
    order(:title)
  end

  def self.by_priority(order = 'asc')
    order(:priority)
  end

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  
  def index
    @boards = Board.all
  end
 
  def show
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)
      if @board.save
        @board.priority = @board.id
        @board.save
        redirect_to board_path(@board), notice: 'Board created'
      else
        render :new
      end
  end

  def update
    if @board.update(board_params)
      redirect_to @board, notice: 'Board updated'
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path, notice: 'Board Deleted'
  end


  private

    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:title, :priority)
    end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = @board.lists #.all is implied
  end
 
  def show
  end

  def new
    @list = @board.lists.new
  end

  def edit
  end

  def create
    @list = @board.lists.new(list_params)
      max = @board.lists.maximum('priority')
        @list.priority = max + 1
      if @list.save
        redirect_to [@board, @list], notice: 'list created'
      else
        render :new
      end
  end

  def update
    if @list.update(list_params)
      redirect_to [@board, @list], notice: 'list updated'
    else
      render :edit
    end
  end

 
  def destroy
    @list.destroy
    redirect_to board_lists_path(@board), notice: 'List Deleted'
  end


  private

    def set_board
      @board = Board.find(params[:board_id])
    end


    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:title, :priority)
    end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = List.tasks
  end
 
  def show
  end

  def new
    @task = list.tasks.new
  end

  def edit
  end

  def create
    @task = list.tasks.new(task_params)
      if @task.save
        redirect_to [@list, @task], notice: 'task created'
      else
        render :new
      end
  end

  def update
    if @task.update(task_params)
      redirect_to [@list, @task], notice: 'task updated'
    else
      render :edit
    end
  end

 
  def destroy
    @task.destroy
    redirect_to list_tasks_path(@list), notice: 'Task Deleted'
  end


  private

    def set_list
      @list = List.find(params[:list_id])
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :priority)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/edit.html.erb
<%= form_for @board do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.submit %>
<% end %>

app/views/boards/index.html.erb
<h1> Board Index </h1>

<%= link_to 'Create a new board', new_board_path %>
<hr />

<ui>
<% @boards.by_title.each do |board| %>
<li>
<%= link_to "#{board.title}", board_path(board) %>
<%= link_to "Edit", edit_board_path(board) %>
<%= link_to 'Delete', board, method: :delete %>
</li>
<% end %>
</ui>

app/views/boards/new.html.erb
<%= form_for @board do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.submit %>
<% end %>

app/views/boards/show.html.erb
<h1> I am your board <h1>
<h2> My name is: <%= @board.title %> </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/staticpages/home.html.erb
<h1> Hello I am your home page </h1>

<%= link_to 'Boards', boards_path %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>